[build]
  functions = "api"

[[redirects]]
  from = "/graphql"
  to = "/.netlify/functions/graphql"
  status = 200

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/health"
  status = 200
